#!/bin/bash

LINUX_MAJOR=6
LINUX_MINOR=7
LINUX_PATCH=4

BUSYBOX_MAJOR=1
BUSYBOX_MINOR=36
BUSYBOX_PATCH=1

LINUX_VERSION=${LINUX_MAJOR}.${LINUX_MINOR}.${LINUX_PATCH}
BUSYBOX_VERSION=${BUSYBOX_MAJOR}.${BUSYBOX_MINOR}.${BUSYBOX_PATCH}