name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Run build.bash
              run: ./build.bash

            - name: Create release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Build Number\:${{ github.ref }}
                  draft: false
                  prerelease: false
                  files: |
                      dist/boot/boot.img